FROM mcr.microsoft.com/devcontainers/javascript-node:0-18

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install git \
    # && apt install zsh -y \
    # && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
    # && apt-get install -y neovim
